apiVersion: v2
name: backstage
description: Backstage Helm Chart para o lab do Nilton
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
