redis-ha:
  enabled: false

redis:
  secretInit:
    enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  certificate:
    enabled: false   # SEM TLS
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.localtest.me
    paths:
      - /
    pathType: Prefix
    tls: false
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  params:
    server.insecure: "true"   # IMPORTANTE para evitar redirecionamentos HTTPS

global:
  domain: argocd.localtest.me   # CORREÇÃO CRÍTICA